[build]
builder = "nixpacks"
root = "backend"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build.env]
NODE_ENV = "production"
NODE_VERSION = "18"

[build.buildCommand]
command = "npm ci"

[build.startCommand]
command = "npm run start:prod"

[[services]]
name = "backend"
directory = "backend" 