[build]
builder = "nixpacks"
root = "backend"
buildCommand = "npm ci"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build.env]
NODE_ENV = "production"
NODE_VERSION = "18"

[[services]]
name = "backend"
directory = "backend" 